"""Initial migration

Revision ID: ab22e3d90e56
Revises: 
Create Date: 2022-06-05 12:09:38.224009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab22e3d90e56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('rg', sa.String(length=15), nullable=True),
    sa.Column('orgao_exp_rg', sa.String(length=15), nullable=True),
    sa.Column('uf_exp_rg', sa.String(length=2), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.Integer(), nullable=True),
    sa.Column('pai', sa.Integer(), nullable=True),
    sa.Column('mae', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=8), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('uf_naturalidade', sa.String(length=2), nullable=True),
    sa.Column('naturalidade', sa.String(length=30), nullable=True),
    sa.Column('nacionalidade', sa.String(length=20), nullable=True),
    sa.Column('certidao_nascimento', sa.String(length=10), nullable=True),
    sa.Column('termo_certidao_nasc', sa.String(length=10), nullable=True),
    sa.Column('folha_certidao_nasc', sa.String(length=10), nullable=True),
    sa.Column('livro_certidao_nasc', sa.String(length=10), nullable=True),
    sa.Column('data_emissao_certidao', sa.Date(), nullable=True),
    sa.Column('cartorio_certidao', sa.String(length=30), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('updated_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('responsavel_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('sexo', sa.Integer(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('tipo_responsavel', sa.Integer(), nullable=True),
    sa.Column('profissao', sa.String(length=80), nullable=True),
    sa.Column('contato', sa.String(length=11), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('updated_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('updated_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_table')
    op.drop_table('responsavel_table')
    op.drop_table('alunos_table')
    # ### end Alembic commands ###
